Repository scmn-dev/secman, pull requests merged in 2021-04, with the labels that each got.

#20 create / command
  .gitignore
  core/core.go
  go.sum
Labels: feature

#21 format / command
  core/core.go
Labels: duplicate

#24 config gitpod
  .gitpod.Dockerfile
  .gitpod.yml
Labels: enhancement

#28 Add a Codacy badge to README.md
  README.md
Labels: feature

#31 Add Forms to README
  README.md
Labels: documentation, feature
